### ISSUE TITLE
Problem installing from pypi on Ubuntu 12.10

### ISSUE THREAD

**Issue by jscn** [django-behave/django-behave#11]
I'm getting the following error when installing from pypi:

```
jscn@ziz:~/venvs/djello$ pip install django-behave
Downloading/unpacking django-behave
  Downloading django-behave-0.0.12.macosx-10.8-x86_64.tar.gz
  Running setup.py egg_info for package django-behave
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/home/jscn/venvs/djello/build/django-behave/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/home/jscn/venvs/djello/build/django-behave/setup.py'
```

It appears as though it's getting the macosx binary, instead of the source. (I'm running Ubuntu, not OSX). Seems to install okay if I specify the version number:

```
pip install django-behave==0.0.12
```

Unfortunately, I don't know enough about Python packaging to be able to say what the problem is.

**Comment by rotherfuchs** [comment]
Just stumbled over that issue today. 

```
(pyenv)drudge:referista rothfuchs$ pip install django-behave
Downloading/unpacking django-behave
  Downloading django-behave-0.1.3.macosx-10.9-intel.tar.gz
  Running setup.py egg_info for package django-behave
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/Users/rothfuchs/Documents/Arbeit/referista/src/referista/pyenv/build/django-behave/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/Users/rothfuchs/Documents/Arbeit/referista/src/referista/pyenv/build/django-behave/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/rothfuchs/Documents/Arbeit/referista/src/referista/pyenv/build/django-behave
Storing complete log in /Users/rothfuchs/.pip/pip.log
```
